use crate::geometry_full::{GeometryData, RwTriangle, Vec2, Vec3};
use crate::material::MaterialListInfo;
use serde::Serialize;

/// One export-ready mesh derived from a single Geometry node.
///
/// # Notes
/// - Triangles are the source of truth for topology and material indices.
/// - Submeshes are generated by grouping triangles by material index.
#[derive(Debug, Clone, Serialize)]
pub struct UnifiedMesh {
    pub source_geometry_header_off: u64,

    pub vertices: Vec<Vertex>,
    pub triangles: Vec<Tri>, // triangle list with material indices
    pub submeshes: Vec<Submesh>,
    pub materials: Vec<UnifiedMaterial>,
    pub skin: Option<MeshSkin>,
}

/// Helper geometry that we keep for forensics/debugging.
#[derive(Debug, Clone, Serialize)]
pub struct HelperMesh {
    pub source_geometry_header_off: u64,
    pub vertices: Vec<Vec3>,
    pub triangles: Vec<Tri>,
}

/// Vertex used by UnifiedMesh.
///
/// # Behavior
/// - UV0 is optional; if missing in a file, it is set to (0,0) deterministically.
#[derive(Debug, Clone, Serialize)]
pub struct Vertex {
    pub pos: Vec3,
    pub nrm: Vec3,
    pub uv: Vec<Vec2>,
    pub joints: [u16; 4],
    pub weights: [f32; 4],
}

/// Triangle in Unified representation.
#[derive(Debug, Clone, Copy, Serialize)]
pub struct Tri {
    pub i0: u32,
    pub i1: u32,
    pub i2: u32,
    pub material_index: u16,
}

/// One submesh: triangles belonging to one material.
#[derive(Debug, Clone, Serialize)]
pub struct Submesh {
    pub material_index: u32,
    pub indices: Vec<u32>,
    /// True if original topology is TRIANGLE_STRIP.
    pub is_strip: bool,
}

/// Material description used by UnifiedMesh.
#[derive(Debug, Clone, Serialize)]
pub struct UnifiedMaterial {
    pub material_index: u32,
    pub base_texture_name: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct MeshSkin {
    pub bone_count: u32,
    pub used_bones: Vec<u32>,
    pub inverse_bind_matrices: Vec<[f32; 16]>,
}

/// Builds a UnifiedMesh from decoded GeometryData and decoded MaterialList.
///
/// # Behavior
/// - Creates vertices from the first morph target (positions/normals).
/// - If normals are missing, uses (0,0,0) to keep deterministic output.
/// - If UV0 is missing, uses (0,0).
/// - Builds a triangle list and submeshes by grouping triangles by material index.
pub fn build_unified_mesh(
    geometry_header_off: u64,
    geo: &GeometryData,
    materials: Option<&MaterialListInfo>,
    submeshes: Vec<Submesh>,
    skin: Option<&crate::skin::SkinData>,
) -> UnifiedMesh {
    let vcount = geo.num_vertices as usize;

    // Build vertices
    let mut vertices = Vec::with_capacity(vcount);
    for i in 0..vcount {
        let pos = geo.positions.get(i).copied().unwrap_or(Vec3 {
            x: 0.0,
            y: 0.0,
            z: 0.0,
        });
        let nrm = geo.normals.get(i).copied().unwrap_or(Vec3 {
            x: 0.0,
            y: 0.0,
            z: 0.0,
        });

        // Archlord assets often use engine/native UV streams.
        // We only take available UV sets.
        let mut uv = Vec::new();
        if !geo.uvs0.is_empty() {
            uv.push(geo.uvs0.get(i).copied().unwrap_or(Vec2 { x: 0.0, y: 0.0 }));
        }

        vertices.push(Vertex {
            pos,
            nrm,
            uv,
            joints: [0; 4],
            weights: [0.0; 4],
        });
    }

    // Build triangle list (debug/info only; topology should come from BinMeshPLG when present)
    let mut triangles = Vec::with_capacity(geo.triangles.len());
    for t in &geo.triangles {
        triangles.push(convert_tri(*t));
    }

    // Build materials list (base texture per material index)
    let mut mats_out = Vec::new();
    if let Some(ml) = materials {
        for (idx, m) in ml.materials.iter().enumerate() {
            let tex = m.texture.as_ref().and_then(|t| t.name.clone());
            mats_out.push(UnifiedMaterial {
                material_index: idx as u32,
                base_texture_name: tex,
            });
        }
    }

    // Apply skinning data if available
    let mut skin_out = None;
    if let Some(sk) = skin {
        let max_w = sk.max_weights as usize;
        let used_len = sk.used_bone_indices.len();
        for i in 0..vcount {
            for j in 0..4 {
                let idx_off = i * max_w + j;
                if idx_off >= sk.indices.len() || idx_off >= sk.weights.len() {
                    break;
                }
                let raw_idx = sk.indices[idx_off] as usize;
                let joint = if raw_idx < used_len {
                    sk.used_bone_indices[raw_idx] as u16
                } else {
                    0
                };
                let w = sk.weights[idx_off];
                vertices[i].joints[j] = joint;
                vertices[i].weights[j] = w;
            }
        }
        skin_out = Some(MeshSkin {
            bone_count: sk.bone_count,
            used_bones: sk.used_bone_indices.clone(),
            inverse_bind_matrices: sk.inverse_bind_matrices.clone(),
        });
    }

    UnifiedMesh {
        source_geometry_header_off: geometry_header_off,
        vertices,
        triangles,
        submeshes,
        materials: mats_out,
        skin: skin_out,
    }
}

/// Builds a HelperMesh from decoded GeometryData.
///
/// # Behavior
/// - Stores only positions and triangle list (still keeps material indices).
pub fn build_helper_mesh(geometry_header_off: u64, geo: &GeometryData) -> HelperMesh {
    let vertices = geo.positions.clone();
    let triangles = geo.triangles.iter().copied().map(convert_tri).collect();
    HelperMesh {
        source_geometry_header_off: geometry_header_off,
        vertices,
        triangles,
    }
}

fn convert_tri(t: RwTriangle) -> Tri {
    Tri {
        i0: t.i0 as u32,
        i1: t.i1 as u32,
        i2: t.i2 as u32,
        material_index: t.material_index,
    }
}
