use crate::geometry_full::{GeometryData, RwTriangle, Vec2, Vec3};
use crate::material::MaterialListInfo;
use serde::Serialize;

/// One export-ready mesh derived from a single Geometry node.
///
/// # Notes
/// - Triangles are the source of truth for topology and material indices.
/// - Submeshes are generated by grouping triangles by material index.
#[derive(Debug, Clone, Serialize)]
pub struct UnifiedMesh {
    pub source_geometry_header_off: u64,

    pub vertices: Vec<Vertex>,
    pub triangles: Vec<Tri>, // triangle list with material indices
    pub submeshes: Vec<Submesh>,
    pub materials: Vec<UnifiedMaterial>,
}

/// Helper geometry that we keep for forensics/debugging.
#[derive(Debug, Clone, Serialize)]
pub struct HelperMesh {
    pub source_geometry_header_off: u64,
    pub vertices: Vec<Vec3>,
    pub triangles: Vec<Tri>,
}

/// Vertex used by UnifiedMesh.
///
/// # Behavior
/// - UV0 is optional; if missing in a file, it is set to (0,0) deterministically.
#[derive(Debug, Clone, Copy, Serialize)]
pub struct Vertex {
    pub pos: Vec3,
    pub nrm: Vec3,
    pub uv0: Vec2,
}

/// Triangle in Unified representation.
#[derive(Debug, Clone, Copy, Serialize)]
pub struct Tri {
    pub i0: u32,
    pub i1: u32,
    pub i2: u32,
    pub material_index: u16,
}

/// One submesh: triangles belonging to one material.
#[derive(Debug, Clone, Serialize)]
pub struct Submesh {
    pub material_index: u16,
    pub triangle_indices: Vec<u32>, // indices into `UnifiedMesh.triangles`
}

/// Material description used by UnifiedMesh.
#[derive(Debug, Clone, Serialize)]
pub struct UnifiedMaterial {
    pub material_index: u32,
    pub base_texture_name: Option<String>,
}

/// Builds a UnifiedMesh from decoded GeometryData and decoded MaterialList.
///
/// # Behavior
/// - Creates vertices from the first morph target (positions/normals).
/// - If normals are missing, uses (0,0,0) to keep deterministic output.
/// - If UV0 is missing, uses (0,0).
/// - Builds a triangle list and submeshes by grouping triangles by material index.
pub fn build_unified_mesh(
    geometry_header_off: u64,
    geo: &GeometryData,
    materials: Option<&MaterialListInfo>,
) -> UnifiedMesh {
    let vcount = geo.num_vertices as usize;

    // Build vertices
    let mut vertices = Vec::with_capacity(vcount);
    for i in 0..vcount {
        let pos = geo.positions.get(i).copied().unwrap_or(Vec3 { x: 0.0, y: 0.0, z: 0.0 });
        let nrm = geo.normals.get(i).copied().unwrap_or(Vec3 { x: 0.0, y: 0.0, z: 0.0 });
        let uv0 = geo.uvs0.get(i).copied().unwrap_or(Vec2 { x: 0.0, y: 0.0 });
        vertices.push(Vertex { pos, nrm, uv0 });
    }

    // Build triangle list
    let mut triangles = Vec::with_capacity(geo.triangles.len());
    for t in &geo.triangles {
        triangles.push(convert_tri(*t));
    }

    // Build submeshes by grouping triangle indices by material_index
    let mut buckets: std::collections::BTreeMap<u16, Vec<u32>> = std::collections::BTreeMap::new();
    for (ti, t) in triangles.iter().enumerate() {
        buckets.entry(t.material_index).or_default().push(ti as u32);
    }

    let submeshes = buckets
        .into_iter()
        .map(|(mat, tri_idx)| Submesh {
            material_index: mat,
            triangle_indices: tri_idx,
        })
        .collect::<Vec<_>>();

    // Build materials list (base texture per material index)
    let mut mats_out = Vec::new();
    if let Some(ml) = materials {
        for (idx, m) in ml.materials.iter().enumerate() {
            let tex = m.texture.as_ref().and_then(|t| t.name.clone());
            mats_out.push(UnifiedMaterial {
                material_index: idx as u32,
                base_texture_name: tex,
            });
        }
    }

    UnifiedMesh {
        source_geometry_header_off: geometry_header_off,
        vertices,
        triangles,
        submeshes,
        materials: mats_out,
    }
}

/// Builds a HelperMesh from decoded GeometryData.
///
/// # Behavior
/// - Stores only positions and triangle list (still keeps material indices).
pub fn build_helper_mesh(geometry_header_off: u64, geo: &GeometryData) -> HelperMesh {
    let vertices = geo.positions.clone();
    let triangles = geo.triangles.iter().copied().map(convert_tri).collect();
    HelperMesh {
        source_geometry_header_off: geometry_header_off,
        vertices,
        triangles,
    }
}

fn convert_tri(t: RwTriangle) -> Tri {
    Tri {
        i0: t.i0 as u32,
        i1: t.i1 as u32,
        i2: t.i2 as u32,
        material_index: t.material_index,
    }
}
